### ISSUE TITLE
@Version cause: update effect 0 row, maybe version control lock occurred due to  condition => `and "version"=null` at the end of the request

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#215]
I am using `org.springframework.data.mybatis.annotations.Version` but it keep breaking my application.

The error is:

     update effect 0 row, maybe version control lock occurred.

I can see that the request end with:

```sql
"version"="version"+1,
where 
"id"=21
 and "version"=null
```

Which cause the whole request to edit `0 row`.

How can I prevent `spring-data-mybatis` from appending ` and "version"=null` at the end of the request?

**Comment by kopax** [comment]
This is not solved yet, any solution? I have tried many configurations, including default value in create sql statement. It seems that something is missing.

**Comment by kopax** [comment]
Using `updateIgnore`, I always get `version`=null , which break all the updateIgnore when activating this feature. Any idea on how I can fix this?

**Comment by kopax** [comment]
@easybest is this fixed?

**Comment by easybest** [comment]
yea, in the latest version, it was fixed.
but... you need to upgrade spring boot to 2.x

**Comment by kopax** [comment]
I am so glad you answerer, I wish I could upgrade to 2.x, I am really thinking to restart the whole just to get the upgrade.

- When will you schedule a 2.x documentation (minimum so we can get started with 2.x)
- Even better when will you spply a 1.x to 2.x migration guide? I think I am not the only one in need.

If there's a way to prioritize such tasks, please feel free to let me know.

**Comment by easybest** [comment]
In fact, it's easy to upgrade from 1.x to 2.x.
But,, you know, it depends on the complexity of your project, so you still need to cost relatively much time on upgrading your project.
If you need more help, let me know

**Comment by kopax** [comment]
I think I will try your example and try to figure out and then spend the time to upgrade parts by parts. If you can give a little help that will definitely increase priority for us. Thank you for the sample demo.

You still cannot state for a real documentation?

**Comment by easybest** [comment]
documentation is writing

**Comment by kopax** [comment]
This is good news. Do you have ETA ?
